---
engines:
  rubocop:
    enabled: true
    exclude_fingerprints:
      - 15684e77a6036a56ca2db7cbb958ab08 # long method
      - 8f5f9fae9dac04fe85d0529021092b01 # long method
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - "**.rb"
  - Gemfile.lock
exclude_paths:
- config/**/*
- spec/**/*
- vendor/**/*
